project:
  type: website
  resources: 
        - CV_Martin_Sjogard.pdf
extensions: [iconify]

website:
  title: "Martin Sjogard"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Posts"
        menu:
          - text: "Quick paper summary: Sleep spindles, motor learning and sleep-dependent memory consolidation"
            href: posts/quicksummaries_localspindles/ind.qmd
          - text: "Developing a novel cluster number determination for K-means clustering"
            href: posts/kmeans-permutation/index.qmd
          - text: "Power Analysis for LMMs"
            href: posts/power-analysis-lmm/index.qmd
          - text: "FWER Correction, background pt. 1"
            href: posts/fwer-correction-part1/index.qmd
          - text: "FWER Correction, background pt. 2"
            href: posts/fwer-correction-part2/index.qmd
      - text: "Papers"
        menu:
          - text: "Hippocampal ripples predict motor learning during brief rest breaks in humans"
            href: https://www.nature.com/articles/s41467-025-61136-y
          - text: "A novel approach to estimating the cortical sources of sleep spindles using simultaneous EEG/MEG"
            href: https://www.frontiersin.org/journals/neurology/articles/10.3389/fneur.2022.871166/full
          - text: "Do the posterior midline cortices belong to the electrophysiological default-mode network?"
            href: https://www.sciencedirect.com/science/article/abs/pii/S105381191930549X
          - text: "Brain dysconnectivity relates to disability and cognitive impairment in multiple sclerosis"
            href: https://onlinelibrary.wiley.com/doi/pdf/10.1002/hbm.25247
          - text: "Quick paper summary: Sleep spindles, motor learning and sleep-dependent memory consolidation"
            href: posts/quicksummaries_localspindles/ind.qmd
      - text: "Talks"
        menu:
          - text: "Disrupted ipsilateral encoding of motor sequence learning in Schizophrenia: spectral and hemispheric aspects"
            href: posts/quicksummaries_localspindles/index.qmd
          - text: "Schizophrenia patients learn normally but do not consolidate: A case for differential sleep spindle topography"
            href: posts/quicksummaries_localspindles/index.qmd
          - text: "Sleep spindle increases follow cortical patterns of task encoding"
            href: posts/quicksummaries_localspindles/index.qmd
          - text: "Sleep spindle increases and Task learning vs Sleep-dependent memory consolidation: Two topographically distinct relationships"
            href: posts/quicksummaries_localspindles/index.qmd
          - text: "Hippocampal ripples and memory"
            href: posts/quicksummaries_localspindles/index.qmd

    right:
        - icon: linkedin
          href: https://www.linkedin.com/in/martinsjogard/
        - icon: envelope
          href: mailto:martinsjogard@gmail.com
        - icon: mortarboard-fill
          href: https://scholar.google.com/citations?user=F59U3gEAAAAJ&hl=en
        - icon: file-text
          text: CV
          href: CV_Martin_Sjogard.pdf

format:
  html:
    theme: cosmo
    toc: true
    css: custom.css
    include-in-header:
      - text: |
          <script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>
    grid:
      sidebar-width: 150px
      body-width: 900px
      margin-width: 150px
      gutter-width: 1.5rem
