project:
  type: website

website:
  title: "Martin Sjogard"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Posts"
        menu:
          - text: "Power Analysis for LMMs"
            href: posts/power-analysis-lmm/index.qmd
          - text: "FWER Correction, background pt. 1"
            href: posts/fwer-correction-part1/index.qmd
          - text: "FWER Correction, background pt. 2"
            href: posts/fwer-correction-part2/index.qmd
          - text: "Developing a novel cluster number determination for K-means clustering"
            href: posts/kmeans-permutation/index.qmd
    right:
        - icon: linkedin
          href: https://www.linkedin.com/in/martinsjogard/

format:
  html:
    theme: cosmo
    toc: true
    css: custom.css
