project:
  type: website

website:
  title: "Martin Sjogard"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Posts"
        menu:
          - text: "Power Analysis for LMMs"
            href: posts/power-analysis-lmm/index.qmd
          - text: "FWER Correction, background pt. 1"
            href: posts/fwer-correction-part1/index.qmd
          - text: "FWER Correction, background pt. 2"
            href: posts/fwer-correction-part2/index.qmd
          - text: "Developing a novel cluster number determination for K-means clustering"
            href: posts/kmeans-permutation/index.qmd
    right:
        - icon: linkedin
          href: https://www.linkedin.com/in/martinsjogard/
        - icon: envelope
          href: mailto:martinsjogard@gmail.com
        - icon: mortarboard-fill
          href: https://scholar.google.com/citations?user=F59U3gEAAAAJ&hl=en

format:
  html:
    theme: cosmo
    toc: true
    css: custom.css
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem
